---
title: "Assignment 5"
author: "Hannah Irish & Nadine Snyder"
date: "2023-05-15"
output: html_document
---

```{r setup, include=FALSE, echo=TRUE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE)

library(sensitivity)
library(tidyverse)
library(lubridate)
library(reldist)
library(purrr)
library(ggpubr)
library(here)
```



# **Assignment 5**
```{r}

##read in data
sager = read.table(here::here("assignments/hw5/data/sager.txt"), header=T)
head(sager)

# add date
sager = sager %>% mutate(date = paste(day,month,year, sep="/"))
sager$date = as.Date(sager$date,"%d/%m/%Y")

```



Make combined metric, which takes the maximum rainfall from the winter months and the minimum in the summer montsh (roughly the wettest and driest seasons), to be sure the function runs well at the extremes:
```{r}

##our metric function, called "combine_metrics"
combine_metrics <- function(m,o, month, day, year,wy){
  
  ##combine vectors in a data frame
   flow = cbind.data.frame(m,o, month, day, year,wy)
   
   ##select the winter months and compute the max rainfall
  intermediate_winter <- flow %>% group_by(wy, month) %>%
    summarize(model=sum(m), obs=sum(o)) %>%
  filter(month %in% c(12,1,2,3)) %>% 
  group_by(wy) %>%
  summarize(max_obs = max(o), max_mod = max(m)) %>%
  mutate(error=(abs(max_obs-max_mod)/max_obs)) ##compute the error between modeled and observed
  
  winter <- mean(intermediate_winter$error)
  
   ##select the summer months and compute the min rainfall
   intermediate_summer <- flow %>% group_by(wy, month) %>%
    summarize(model=sum(m), obs=sum(o)) %>%
  filter(month %in% c(6,7,8,9)) %>% 
  group_by(wy) %>%
 summarize(min_obs = min(o), min_mod = min(m)) %>%
   mutate(error=(abs(min_obs-min_mod)/min_obs)) ##compute the error between modeled and observed
  
  summer <- mean(intermediate_summer$error)
  
  ##equally weigh the two error averages
  combined <- 0.5*(1-summer) + 0.5*(1-winter)
  
  ##return a list of each average error as well as the combined metric
  return(list(summer=summer,winter=winter, combined=combined))
}

```


```{r}
source(here("R/nse.R"))

source(here("R/relerr.R"))

source(here("R/cper.R"))

##reade in sagerm.txt
msage = read.table(here::here("assignments/hw5/data/sagerm.txt"), header=T)

##gather data to label 
nsim = ncol(msage)
snames = sprintf("S%d",seq(from=1, to=nsim))
colnames(msage)=snames

##copy everything from sager over to msage
msage$date = sager$date
msage$month = sager$month
msage$year = sager$year
msage$day = sager$day
msage$wy = sager$wy

##join with obs and date
msage = left_join(msage, sager[,c("obs","date")], by=c("date"))

# subset
short_msage = subset(msage, wy < 1975)

##compute metrics for all, using our made metric function
res = short_msage %>% select(-date, -month, -day, -year, -wy, -obs ) %>%
  map_df(combine_metrics, o=short_msage$obs, month=short_msage$month, day=short_msage$day, year=short_msage$year, wy=short_msage$wy)

##put in the simulation names
res$sim = snames

##tidy
resl = res %>% pivot_longer(-sim, names_to="metric", values_to="value")

##Plot so you can see summer vs winter
ggplot(resl, aes(metric, value))+geom_boxplot()+facet_wrap(~metric, scales="free")


best = res[which.max(res$combined),]

##look at how our best simulation performs with the metric
ggplot(msage, aes(date, msage[,best$sim])) + geom_line()+geom_line(aes(date, obs), col="red") 


```


```{r}

##calculate the worst also 
 worst = res[which.min(res$combined),]
 

 compruns = msage %>% select(best$sim, worst$sim, date, obs, month, day, year, wy)
 compruns = subset(compruns, wy > 1970)
 compruns_mwy = compruns %>% select(-c(day,date, year)) %>% group_by(month, wy) %>% summarize(across(everything(), mean))
 
 ##plot the best and worst simulations
 compruns_mwyl = compruns_mwy %>% pivot_longer(cols=!c(month,wy), names_to="sim", values_to="flow")
 compruns_mwyl %>% subset(month==8) %>% ggplot(aes(sim,flow ))+geom_boxplot()
```
Best parameter set is S32, and worst is S8

